# Generated by Django 2.2.3 on 2019-07-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('background', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
