# Generated by Django 2.2.3 on 2019-07-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0002_headermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
    ]
