# Generated by Django 2.2.3 on 2019-07-04 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0003_contactmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='title',
        ),
    ]
