# Generated by Django 2.2.3 on 2019-07-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0004_remove_contactmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_sessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('background', models.ImageField(upload_to='media/contact')),
            ],
        ),
        migrations.AlterField(
            model_name='headermodel',
            name='background',
            field=models.ImageField(upload_to='media/eader'),
        ),
    ]
