# Generated by Django 2.2.3 on 2019-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0005_auto_20190704_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.CharField(max_length=255)),
            ],
        ),
    ]
