# Generated by Django 2.2.3 on 2019-07-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0006_about_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermodel',
            name='background',
            field=models.ImageField(upload_to='media/header'),
        ),
    ]
