# Generated by Django 2.2.3 on 2019-07-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0008_portfolioitem_portfoliomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio_item/'),
        ),
    ]
