# Generated by Django 2.2.3 on 2019-07-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0009_auto_20190704_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodel',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
