# Generated by Django 2.2.3 on 2019-07-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancer_app', '0010_portfoliomodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_session',
            name='image',
            field=models.ImageField(null=True, upload_to='portfolio'),
        ),
    ]
